spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codechella_db
    username: alura
    password: alura123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

hibernate:
  dialect: org.hibernate.dialect.HSQLDialect